# Many thanks to @timkicker for bringing a previously commited secret to my attention!
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/yuvipanda/pre-commit-hook-ensure-sops
    rev: v1.1
    hooks:
      - id: sops-encryption
        # Uncomment to exclude all markdown files from encryption
        exclude: \*/secrets/keys\.json
