apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:HaRkgnn7m4lVdGTy3ltTvFFhEg51,iv:HeJtilfU4hEIKjvES+4MVVN7mJA+Js//yllfYPUFGGs=,tag:0n9P3UV2lLkdJ088i/iHKw==,type:str]
        privateKeySecretRef:
            name: cloudflare-issuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SkJCeE1RdW9yeUoxbkJ0
            M3FxZzJkMnAzNHV2UzJWcjArN0F3Z2IwS2xrCkFld3hHK1VRdTVVRnNmR01jdHN2
            UHBQQTdkSzZHVkw2cHgvM3hjbFBlbncKLS0tIHVOaDRYM2J1eDg5OU0vMTJocHBk
            V0JkRFRQN25pWXN5N1RWODJJcW91b1EKGLqBDSSCjqnmPYXF7yN64F5li2PPHbTT
            Ar5VpjzB6aMstyW2biH1TRIp82w7eZ8aXA3SE5KZ9tK2FB3ec4x7FQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLQ0Vodm1ZeDU5L3NqWThG
            K3NVTFU2ekpVUzBKdU5kbVJwaDhTaldkSlcwCjJUbjI5VFlVYndVRkhvemtvbjVm
            dUJtb2ZLczU4S1psYXZuWXN0TXViUzAKLS0tIGY0dTNTUElPbmJMM2hvMzlZY2Zz
            bkFDSW45d213cTZNdUs3Q2ZzM1RQVUUK/SHF88lX1YzV7edPyYok/yE+M+pZiMM7
            3HoSP17RCch4s+jTb7So1mDkChi1BGJBQUthTtkYo4lpp8k8LhSvkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-04T12:13:32Z"
    mac: ENC[AES256_GCM,data:qmELS5NkYJp3kxUCzJN8KJOSfFttFnmUXe+upHY2H8jrC4nhvqUArqyOVQiHDcTY4HXuvHxP7jNeeAlLZCbW3ghvvdV0AM5LE0K+zsVc6SB1+mPXEirbkNhpAh1mvcm5SGmR7ma1PAnk+jZ72y2IP4D9Vm8H/2o3a+xDTN7eIAk=,iv:bVQCBJChQweh6KmCYVeYJVoJlzI78H1fo88PSUyuzTc=,tag:bXXmI8MXfuTnK0+zt0JzRg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
