apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: cloudflare-cert-issuer
    namespace: cert-manager
spec:
    acme:
        server: https://acme-v02.api.letsencrypt.org/directory
        email: ENC[AES256_GCM,data:HaRkgnn7m4lVdGTy3ltTvFFhEg51,iv:HeJtilfU4hEIKjvES+4MVVN7mJA+Js//yllfYPUFGGs=,tag:0n9P3UV2lLkdJ088i/iHKw==,type:str]
        privateKeySecretRef:
            name: cloudflare-issuer-account-key
        solvers:
            - dns01:
                cloudflare:
                    apiTokenSecretRef:
                        name: cloudflare-api-token
                        key: api-token
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSMUNSbVBadEtYMkEraTBB
            aEpEU1YyNCtYQjFRNGZiSUM5ekdzME5wblY4CjNhKytab01qM3UzaW95OWdFcFNa
            RmlQVGdzcUJMdE9aaHU4b1EvQXdkSU0KLS0tIC9YbWlFOHRNMmx5Q3E1YktkOU14
            T0YwVUxHa0w4RE9HT0J6TkhZTlUzUXMKCF6Cr41yeD1+AfJYmbq3764Lu6fHxlem
            GVIal/qiYF4cYtGzaFIVMSNeUEgZVedsO1Pn+FfEKTGhwrSFlwOyTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TnE4eCsyMFpicHlJcUN6
            cVo0OVNJQ25ybVpMVGI4SnBNc0ZSM25QbHlNClRjb05MWkh3cGU4UEJHU1dCaHZL
            eEZRZlQ3TGdCbjl4UVdlSWR5elpzWjgKLS0tIFhuU052Z2ROYjNsUnphRmpqajQw
            Z0NUQkpJdm81blMyNFZiaWZ6NjZybzgKdvW8qP+wE3Nqvt3AyeJQ+Ur4FPsyQ4T2
            KR5i664losSzqxFcgXa14q6SXe6WC4rS+TsE7YkaQlFno/6GVQIGvg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yacmz82gdmwvm5ecqmanpdsshdts240fprqdsht5xsqmyx6e7qssjlcu2r
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmT2hVSTVxbysrRk5KWUp4
            ejhhbWtLMXNHa0FhU0RmRTVRNHVMdWIyMG44CkJhQnpaS0RHZW5ST003Z2RwTDZp
            QThBa1VLa1dVVWNiSEhOMEE5c2FuZWMKLS0tIDN1NzFnOVlYN0xwSHlHaGZmdjhv
            MHpMVWxCb1QvNExveWttSmZELzFWTjQKs543OTsd2GNn6XqPV+R780ROE3t1dJzE
            i1EiiZC40fYgQg4YyE9FCvNT3Z2kamAYIskIcqow5Z1LoVGR7kTn6A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
    encrypted_regex: ^(data|stringData|email)$
    lastmodified: "2026-05-04T12:13:32Z"
    mac: ENC[AES256_GCM,data:qmELS5NkYJp3kxUCzJN8KJOSfFttFnmUXe+upHY2H8jrC4nhvqUArqyOVQiHDcTY4HXuvHxP7jNeeAlLZCbW3ghvvdV0AM5LE0K+zsVc6SB1+mPXEirbkNhpAh1mvcm5SGmR7ma1PAnk+jZ72y2IP4D9Vm8H/2o3a+xDTN7eIAk=,iv:bVQCBJChQweh6KmCYVeYJVoJlzI78H1fo88PSUyuzTc=,tag:bXXmI8MXfuTnK0+zt0JzRg==,type:str]
    version: 3.12.2
