apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:1ApgY2dVS0hoXkc+JfTR5wcj6ZjQMgrlJRuFT/YYCDMvy0tPmn/i5w==,iv:kCiAd00MjBlyAwT8UlZ8G9hcZBaxsJWxfA+Edqq4k48=,tag:C6lNHvgFyX3DTYPAZKV6aw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGVmtZWXkwc25tbFpzV3lW
            VFpabmdMY3JTMGRnSWF3S2dJb05EOE5OL1Y4CkRRWEpCVndNQ2Z2Q0ZXTHZQVnp2
            TjRvSHlQaGE2U3Z0VWlEOFNLa2YwcVEKLS0tIE5NZm1uRGlMa0xZbVh5SmFseFRh
            eDBxdmtFU3psZzhWVkJYUi9aRWpOdlEKjgXnaubEWq2VJPqtkFoNC3to2OVsKKVo
            5RovaUWcJC4srlEYk6dLD5xGMCOHS+nhda2yacof1ELYUwvCoxsioQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYXFVQVA2NUxmenJIczJM
            bWNLWTl2b0VHWHlMWEY2Y2w0YkNzS1J1YlJBCklxbzF2R3JPa2k4dE81cTBRUVh4
            TDRZdXM1WjUxUjFHTEZOcHcvWnAzTm8KLS0tIEU0Zk9uWlZJMzcrTEVQQloyaCsw
            UHdQS3pQV1luemlSbDRzYmhuMzlWVDgKq3zXqaK6xVqjQJVt2hl9No+9obUcLTCJ
            o+gw8c3a08TZEtxiKtNqIo7ZtkSnSmKV0fvoUyqXRju4s7sDBqRCIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T11:21:04Z"
    mac: ENC[AES256_GCM,data:Yt5DiMQGQXlAUXUjgqD9rn6WXAxuqUBNOmDh/l0a+dPmf8iz/IIWU/3gOvfZoFrjMpI+hZtpZHxMqbsyozMkIW1zOl8qDzcfvbXRc5Ut6sqZU8vOYKR1VZrEpERs7V2TlRQLqZA8ZJPLfkG0QKncrfTevxNwUz2PtxrZHKR5WNM=,iv:+oNQdWEZAE5ZSDb2iLbZ8iJtcpkZAbw/KV9pPkipRM0=,tag:8xyQhyZWx6wJi1rQePtWag==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
