apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: cilium
      version: ^1.19.1 # Update this to match the version installed by your CLI
      sourceRef:
        kind: HelmRepository
        name: cilium
  values:
    gatewayAPI:
      enabled: true
      hostNetwork:
        enabled: true
    # ingressController:
    #   enabled: true
    #   default: true
    #   loadbalancerMode: shared
    #   service:
    #     type: NodePort
    #   insecureNodePort: 30080
    #   secureNodePort: 30443
    envoy:
      enabled: true
      securityContext:
        capabilities:
          keepCapNetBindService: true
          envoy:
            - NET_ADMIN
            - SYS_ADMIN
            - NET_BIND_SERVICE
    ipam:
      mode: kubernetes
    # Masquerading: use iptables (NOT eBPF) to stay KubeSpan-compatible
    enableIPv4Masquerade: true
    enableIPv6Masquerade: true
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445
    # Need this, because otherwise flux gets stuck in a single-node env.
    operator:
      replicas: 1
      rollOutPods: true
      updateStrategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 1
          maxSurge: 0
