tailscale_auth_key: ENC[AES256_GCM,data:d724MjmlGLSuLIac4x8hRPX+WLswN4/x+oXyXbyA2jURdIu6At4bID5XaaCQNNTCmIqaQLontnNNo7eChh4=,iv:YebbXb0dDRuki1zNqMgsRioKc940WNko9Y5fh+jXQP8=,tag:7Hq/ujpvWgiMMKfnblVH3Q==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMGVmQmlNa0l4Z1pmeVRz
            eVIwemZQY1Y4TGVDMnZldHB1OWpLYVFpNkNRCkp1anhMK2ZncjBUVVp2NlVEamZY
            MVZ4Rm85RWlRZzNkTEQxOW9Gdk1LcXMKLS0tIExWenRlMUh1N2plN0xueG03bUph
            KzVTVmZHRytTZUdKUmVGcTVxbk5nNVEK+uwAdsHtzgGLLAn047HVshrG0rnrk4GV
            wmRTVmg0uFkmnEgNMcWNVtssbEWHp9XAfwZ6X3E4QveNSAUM0qmMhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T14:00:14Z"
    mac: ENC[AES256_GCM,data:Hc5nw54Qa8cvuTLtEVluaRMSPHjwYODHiRbBw+me0mhwxcfPF9OIXa/sY++vlCIMW+MfxxlEV5IQlsO73pbo+GOW5aj14MAV6syJZ3tVW7b3MXlKPIDbRUWrWVlDeyiN4WL3naa/5TF3DBhQMmOH7F0mQ5qkj6mLcbNq5e+DWco=,iv:0DvURMmnXM/sBoU1/cGIbEvvh3bSumMwZUhDZEnEDas=,tag:fqCZHpuwZZ2y5O2b6Zioag==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
