tailscale_auth_key: ENC[AES256_GCM,data:8GWcruOCeIxLG2iSaPQdlcoGJX9p2IJVzA5hoVUVOoCEM5qe/YRF+j1Zxszs7zqgrWCkxYSMI9ijBr5iNb658wQ=,iv:cuRY3lfeaAl9oRPfSVA97iKx2krCKWne3FtB7CQvlgU=,tag:x2RN4HotTjd1hqivPd6a2w==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArMGVmQmlNa0l4Z1pmeVRz
            eVIwemZQY1Y4TGVDMnZldHB1OWpLYVFpNkNRCkp1anhMK2ZncjBUVVp2NlVEamZY
            MVZ4Rm85RWlRZzNkTEQxOW9Gdk1LcXMKLS0tIExWenRlMUh1N2plN0xueG03bUph
            KzVTVmZHRytTZUdKUmVGcTVxbk5nNVEK+uwAdsHtzgGLLAn047HVshrG0rnrk4GV
            wmRTVmg0uFkmnEgNMcWNVtssbEWHp9XAfwZ6X3E4QveNSAUM0qmMhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T16:43:52Z"
    mac: ENC[AES256_GCM,data:JjwEYoSBWekbsuhhhsf8ZvfdJs4BywkM7EqF9wI5/kOkvzMN3eDHDD50O6R6lkaGrX7LJh2rDz4rElwob8HNpYJhoezD0IODql0BDglQzyzcdnvJiT6fstz8yf0KPJVQelKajs8rCiQNcyW6qcbF2RlwprIBDPHzl8oSh7lV2eA=,iv:NUwx4YqlDtQZedSvUi3uAHqvUXciRyCQusHymsvMR8s=,tag:td7eV4TLNjNzoBQZS7IYIw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
