keys:
  - &maintainer "age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f"

creation_rules:
  # Secrets in infra
  - path_regex: ^*(secrets|\.secrets|\.sops|\.enc)\.yaml$
    key_groups:
      - age:
          - *maintainer
