clusterName: homelab
talosVersion: v1.12.0
kubernetesVersion: v1.35.4

allowSchedulingOnControlPlanes: true

endpoint: https://api.cluster.netbird.cloud:6443
# This applies to the Talos Machine API (Port 50000)
additionalApiServerCertSans:
  - api.cluster.netbird.cloud

cniConfig:
  name: none

# ==========================================
# GLOBAL: Applies to ALL nodes
# ==========================================
#patches:
#   # Inject the Netbird Setup Key into every node's environment
#   - |-
#     machine:
#       env:
#         NB_SETUP_KEY: ${NB_SETUP_KEY}

# ==========================================
# ROLE: Applies to ALL Control Plane nodes
# ==========================================
controlPlane:
  # Netbird extension for all control plane nodes
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/netbird
  # Inject the config specific to the Netbird extension
  extensionServices:
    - name: netbird
      environment:
        - NB_SETUP_KEY=${NB_SETUP_KEY}
  patches:
    - |-
      machine:
        certSANs:
          - api.cluster.netbird.cloud
    - |-
      machine:
        network:
          extraHostEntries:
            - ip: 152.53.149.109
              aliases:
                - api.cluster.netbird.cloud

# ==========================================
# ROLE: Applies to ALL Worker nodes
# ==========================================
worker:
  schematic:
    customization:
      systemExtensions:
        officialExtensions:
          - siderolabs/netbird
  # Also inject for workers
  extensionServices:
    - name: netbird
      environment:
        - NB_SETUP_KEY=${NB_SETUP_KEY}

nodes:
  - hostname: ncvps01
    installDisk: /dev/vda
    ipAddress: 152.53.149.109
    controlPlane: true
    machineSpec:
      mode: metal

    # Define the schematic HERE for node-specific customizations
    schematic:
      customization:
        extraKernelArgs:
          - net.ifnames=0
          - console=ttyS0,115200n8
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/iscsi-tools
            - siderolabs/netbird
            - siderolabs/qemu-guest-agent

    patches:
      - |-
        machine:
          features:
            kubernetesTalosAPIAccess:
             enabled: true
