apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp-values
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:b70ePiA1g1Ckc7zlFn3qkegpEJRjsWsEhH4xQyvKorZB6nCSF3hk0FtkBJ8u6vzoVBToQCH7QodY0Fd/UH4aFtHreBSwTjRGk9BDVv0fIryVb8OIpdXjdTfoyr7lMyOVwIVhKLOYHNs6fbquR5o540V93kxqm0fuQdTsZNIHIHFoOlYVKAwhTeoZKqZ04PlPEM3C/eZ9SxS20DSfwcsBdl7uM8w/toqN5+cYa1GlTp+mnvqNCUCsheKQAC4b3+0YDdn0GNR7+N1sftDFMf9jM5NyoTofDAu4adjRX251gkgVCyMBscO+xiEoZOaT7ArjjqZF9c+0XPstSNa0K7hv9diMiwn71XenRb/mMl5ymaLL/g3N5xvC/uZiVRfCwIA1bkQprA==,iv:Rhe/IKLbh9YszxqW1YojKv/oBYCK0O8UaKxsa4wA7jM=,tag:Vu2JVOoYIJU6Xsq+MxPbNw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzTTJPUDFyRHBCVHJZa1RW
            dXowWHpwaWQ3N2ZpMVlZaFpIVkJxTGZnbTJjCkNCYkVCa3hMMmV5YzF3TjJrRkpp
            aDJXbExSYk41Q2hhOCtwelR3SW5nVkUKLS0tIHJiMS9NZUxmclNHcDhJTFI2ZzhD
            RTYvbHJDNFBJSzdiN0xrWWdZbmZtem8KryM0VQLNdKZ+kM+cIal/FAYd3EUzqQBj
            DkBm7tWuNvcWvX5mpQpAdwccwpff/E7bRLGLhR4pRNFMx8hjrP9vcA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGV3p4SzVaYTBWaTE2cWY5
            UGhzRnZHN2lrSTBPSU8vQzl0dGc5Zm5CL1JRCjRKSGZ3bmxXcE1UN0VrZHBBZHF2
            TGpsQW5VaW9lbHpUYW9BZnpuMVNEOTgKLS0tIDJjVmtGeG1EM1pacWZLQjVkcmN4
            N3E0OXJRZlM0Q01YdWg4ZmFGdWZoTlEKzHxfJyCj4Y++A4ULPQ5K2onY8+JViNvT
            loi1qFyJ9vFMbGbfIpUu4DWwHFSUzyRIdbeto25cHjBwnel+ANTn4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T23:36:05Z"
    mac: ENC[AES256_GCM,data:K/9S5v+Hba1C2+R3HIvp1BVQTO6bu9AF7CUvDBqzGDCC2kZEEZnJHfs+Dm7F8QFNG8VnhiIrDiaUHSCN2PFAHn8Qdo2/E4hkRWfAuBN3fAa7i7wuUJRfJqP0LfLq14HibJxQWUbBHtYjzciULs++f5rQhWrAmRux+e3/SoBTNFU=,iv:lGcqKpwaSj+6bkgMOyffdc+yCNk5407wJTbuYYJ8g2s=,tag:BoZtNq0JINi1AmBOI4ykAA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
