apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp-values
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:i7Mje8q1H58xZY3ykp2QQIyNMr2O2utuyzV6vUzMtiIp19TkoGf93dUaW/RJ/ZMGCKcYQRI3qD9Fe4ESKg5koWqDcRfMDSQe88FJXtpOM0QpsBOLq/gCdPXME3YXBv8rrwznwfLI06S8+8vB7WzOpbI3+IyPICb3xLGZ7cH76L6f5TOxV+rldPPCYwrGjKQuaznfdPkWNEvbOs+JnHKy0LDtP/ic4ya1/CD58pdLryZMQL7ihMG9V0yKZP2m61ZmtDhgkbuspupjUedFoEst2Vpr0Oun0P2a9rL86M4nPkrRybRFKw5T57rHC+s0D57uiLEwOgTRTjFO3aDqMYdCrZMR6R4kQKfb,iv:PU9Fr1i5CgA/fqEvDFoLq3azRFvoCz/2QZvuF5bLYwY=,tag:fNNqwH0AtPU4dyULpvmDNw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0lyOXZ4YkFZMVgwWHBH
            bnNEN3doN3NhTHozRnBEakhqSGc5R01iaDFVCmpqNC8vN2N0N0o1VEttSUx6YW12
            MGU2RFRkTWVxdG15dXNYNHBreGtEUlEKLS0tIHBBVlcxQUxxQmtFK1IzWEJLbUdB
            MFJ3ZURyNWJ6cXV2c0dlOWc1dENMTncKCaXzOBclnP63iO7At9XCjBHJRNMT/6mm
            CkRqS7Ml+bKn3KGS5OpKDSGoQbJrb+rmMXpZk/yIjiZK0W9oSR0eew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIalpQemNHV0JMQlRKSGFo
            dnhRdW5BV0l4Z2wyM2x5U242cEpTUk5FMTFjCnhSRjl0ckdZQjVFT003eGJ5NGRP
            OHdaU2RJYmFvMzAvRk9rK1lVZE00Z3cKLS0tIE5DT2tJSm9SK2dYOGUxZlg2SHFJ
            Ny9qaVVIRmRUR1A0dXF6aC9yeGNWaEkKLnjXrK28Lnw3ABJ2GGkQF4qoQYdy5oKD
            O+w85bB5TFDHqlmRbSJ/wreNtkJC7j4lErI51KanGB7ttMsgG3mF1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T20:44:17Z"
    mac: ENC[AES256_GCM,data:QvDN+3PdhVAIRFE3iY1zFP2p4p5Y7d0cKhbSZiecphEZJYvlKp3d15VNiWeLtYA7qX1lH8o2QHokbz9q69HBP2SoXPGV3wgMYgh4BlVIYvrJzRi7Lczp8BmXbG3zZWC7P7tIhiIVHIoOxlTJPWjhpe4ZwBg+DJWH954CPWrB+E8=,iv:RYg3cMlPsdASUH0F6joeAqSg/yjDem3WYTknTNoJQaw=,tag:ln6fd22tm4YUXt2cAyHyDg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
