apiVersion: v1
kind: Secret
metadata:
    name: authentik-smtp-values
    namespace: authentik
stringData:
    values.yaml: ENC[AES256_GCM,data:ASLf4KMXkWQfEs/kmd21wvlaGW/VMCVOs5JW0qcyQ3H/kaAM487h2tLFmwrkyu26cQYojZ7lh0flPsmfpLxjObS0ak3rU/R68Nn+tHeU9a7+fxqtDyHQG4uH0Fzkx/xI/v9rSHY+IiLe6i3yroFZzpmDxvAcN3L/hMP78HSE4E00BFWowXIV7xO/nSPz0okbZgWV09HF1cZbdsgh7H82cseTdUlHewHdoWUVpFcPQAB+uTEubEoAkAKe5kl4B5Oo6zcUmUEl1ZHVTs9n1Ph1roYeQkuXsuhzuH2UeDATeFOgFzGjydAWRRGvec3gi3Ntj0xwKDhrfB8gd1GIZkZvuqaBdv+CfZJxLWCkye1KyWoyxip0rqcwuTmwlm+sQYmcLks2Ew==,iv:PJkw/LDq9e/D/CHsGLnDAZvRqPg/6+6ADHRevgfyNFo=,tag:9N3FDFVNppG3j7plDlpP9w==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN0lyOXZ4YkFZMVgwWHBH
            bnNEN3doN3NhTHozRnBEakhqSGc5R01iaDFVCmpqNC8vN2N0N0o1VEttSUx6YW12
            MGU2RFRkTWVxdG15dXNYNHBreGtEUlEKLS0tIHBBVlcxQUxxQmtFK1IzWEJLbUdB
            MFJ3ZURyNWJ6cXV2c0dlOWc1dENMTncKCaXzOBclnP63iO7At9XCjBHJRNMT/6mm
            CkRqS7Ml+bKn3KGS5OpKDSGoQbJrb+rmMXpZk/yIjiZK0W9oSR0eew==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIalpQemNHV0JMQlRKSGFo
            dnhRdW5BV0l4Z2wyM2x5U242cEpTUk5FMTFjCnhSRjl0ckdZQjVFT003eGJ5NGRP
            OHdaU2RJYmFvMzAvRk9rK1lVZE00Z3cKLS0tIE5DT2tJSm9SK2dYOGUxZlg2SHFJ
            Ny9qaVVIRmRUR1A0dXF6aC9yeGNWaEkKLnjXrK28Lnw3ABJ2GGkQF4qoQYdy5oKD
            O+w85bB5TFDHqlmRbSJ/wreNtkJC7j4lErI51KanGB7ttMsgG3mF1A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T22:18:42Z"
    mac: ENC[AES256_GCM,data:zSQqf0Tv/DUAKO+ZH7mDF+J3hd0oZJ8p637n3SRP9c7ackpn2/eR9mjlTWWHt00mbeLAWAozXPij8JJGq3Q7YOqFh6IVtZjYCgWohAK0o+glutHMnpaxxoga4B7Suby+iHLv5p7AX/lSufdP5hPoGCgHFKwxo2aQmDpMed0NWRk=,iv:zfRS5IxSGESH+P5U8EW+zihlWTK+nDTQcOVTdM6GEuk=,tag:VQ8L2Eg9tSlKFN4KGhMwTg==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
