apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - cnpg-cluster.yaml
  #- secret.sops.yaml
  #- helmsecret.sops.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - referencegrant.yaml

secretGenerator:
  - name: authentik-smtp-values
    namespace: authentik
    type: Opaque
    files:
      - values.yaml=helmsecret.sops.yaml
  - name: authentik-secret
    namespace: authentik
    type: Opaque
    files:
      - values.yaml=secret.sops.yaml
