apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:7KbwsHi7AtBwGBi0ClrnevYydh7LPLQlL81aIZ/7uHZjonpeQPn9eWUos9AguapjKmoZxeEesqfw3UTU0xEIbhIkt2TfeNmwirkykhesuzo=,iv:QiQ4f3RXFqoNvU91ceJkEV6IY2oDrCHYh7xJvmHhCik=,tag:VG2O2av2SGeLv8H0tUXQEw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZWJoelEraHlTc0tZazhW
            Y3VJOHorVVZFd0RhRHovV3luWTdhaFhZelNJCncwTkxYQlBnYlllUXpkYUQ4d1BO
            SXUwNWVDZEpGc2pqKzlUSDVsTWtnQVEKLS0tIG5peVJsUXp2NlFjTUNWbEFiM3B5
            Vk9mbG52UE8yZ0pnNmp2dkF4QzAvcmMKFRxFsi8Cr3S/44BKSnI7JoregI853GWA
            mRE9uKZWsp0L+WVn9+K7cMIn/EhIccrGtes5NYAt9KcGm07brPg+PQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0MVNnaXFxTnAwN25Ba2V0
            NGRWd1NoM1hyUkt2bDk3T0FGZFk0RkZsRDM4CmZVL0liUm5NVDBkS1ROV0ZtTnpX
            R2hvM05obEVzRVBGYmdrcTViaVJsUUkKLS0tICtzdVdlam5Sa1I1MTBZKy9yQWs4
            WURCWUJaRHBSNUR6amlYQnhzdnhnL0EKbJnJ1hPOsHUHZefm/c6+VNJnp/RTI//Z
            89ae4hieEa9WMg94rWwClI19dkV4yD4lV2xRrU0gO6t1RLGKpEU1MA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-29T08:58:09Z"
    mac: ENC[AES256_GCM,data:K4z3kBYCeuTWq3viNLGBJPOL2X12Nn2oWVMy4XvptVPa+nozT5mLHBkiyAPI7dIHLKeyBDqQOXQlfyTn8UJqCTkNjKdEEMrJL96aAwTw1f75Lxa+OzAG+r2CelQ30GERXPHFDtDoeBHCuNa/P7sj8tVkCE245iG5kfS9f3yvcFU=,iv:NytB9wQRIarbQeIkpKAfbcsebvIs4D/2eGeFhT4ffok=,tag:ZrjdnnRsIvpRgnYPJ5b1ZA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
