apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:M6ieibh4HEESThqTyl+p2R5TG4eD/PLzsaJS+/5eMPyIZuyaNJp1z/1CJe7bl7g4xtxDWKq0o63//06qdIumiYkiROahcOxvg59bvtCym4A=,iv:00S7BBDSIGJPQWf8eiEJsLZuFf6UzaNifJZHXZIYpBY=,tag:dbG9Vde6Kx4wgXfL0SEz8w==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:ckkjIWtKzGSeBUImY0Qb,iv:E5GpTQebEyNW+rl6bmzTHZjA/IWYvO7xZwHttMvhb1s=,tag:REdrs3SzqjNLS47CO/LT4A==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:gyqraw==,iv:dPwTLPciIJYxoFXrJvXPskc7wkoVz1OA7c0lwhD/0HU=,tag:mnr1VTRLYtvuGX9qx4iEZQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:LQYcnE3BA7iO,iv:LATVuDzShwPMVilQeT+t6a20SI6RaP0SkkndRDY9QeM=,tag:1Okv8lpNPLxdHYN1u7mwJQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:kNrubLTBeIC0DD06USy4rNyMAwI9T3Rfc82iswoFYQ==,iv:N2GebAy7g+w66WrK1nhGWudL+BLklZJrZJ/HftoNxgE=,tag:rQJqKTCWbtnWZHIddKKDFA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:oze6LeGO1Isw+VJoFYV8PF35yIuBFLOlp/mXxrGg3g==,iv:icGI8kHTAOpCnQbLSaJLyfPJFBeBlvWOifKzbPQMQ/o=,tag:60AViQToqepXZ1TxcAmNJg==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZdktibTFqekp4UEt2KzUv
            T3NFUXJXcDREYmhEZjRlOUZGSE1Cbmd5UkZrCjJxWE84bTNnZXd3MGVPVm5BZWFD
            a2ZlaDUxQ2tYTkphRDI0Qm1Qa1JwTE0KLS0tIHZ2QU1DajBtMWtFOFRuenlGQWlJ
            Wkd4dUJaa0pReGlMWml4bHlPc0VEZnMKAIUN5v2gfZjZzYc37viv6TIGTxSIfyib
            Yyl5caaCuqnGCyo/h07BaLj6j3n8f5Pd5F9w2r6ZT/Ao7QDJGBkeiQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqL2VYb3ltMis0SzdSUG5j
            NXRhaHM3MUVQUVUvdGtPQjc0UzBGTXBLTDBZCnZyYzdHQ3Ywa0IzSFR2K2c0bE1u
            WWtJVmFSZVlxNEMvNlFnQ2xWKzIrM28KLS0tIG5FSDh3blMzM2ZsWjJNVEZiNmR0
            Mk9MNE9wQmRoNjlBWEkxRFVnMFRmU2cKD9+PVKPC7Vodze+mhGPaMZokDPXGsEyv
            +K9y5d+eWN6+SvNdcTRwz1Y4pZJw0Q77EnZ8Xqr3i8pgP7bdHSdepw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T22:55:22Z"
    mac: ENC[AES256_GCM,data:Xy3ZRH869s3PmjORHNttzyIVtToItxeIuMsR7Lv/DDsLHnJQUQDElvyE+yb/7Qqeb/3MlqfYromfC0GahT5wW+8FzYO39NMy8hRaNOxTuKifWpEaABCiPqJmIwus+dJDOKVnJmPZ3Ap8XfxK8tNoKbgOW2kZcHOTKzH1a5B6sRQ=,iv:A345x/EG9uyHv2PXLH7V8mBj2p4tKHrKPOHqVYd9NhI=,tag:0S0oa73gKTWtxr+r8IcoAA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
