apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:curb5QWcur6w8KSkW8miuH0/8qVqnwTspW+WJgmtr2EBBFsVm2uVILfrLxGok4kFO2jPSKN1V0JL9kjsLXMc3rPIigwXX+nHizrvILt/c38=,iv:b2+I9WxBCzUKK3p7iffPAnTGxPuZT00icpq0Rwfs6pk=,tag:TfS3yypMQcrHBc0hP5LfiQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:XRz+++k0ADSeZ2teeQbJ,iv:ylPj1XGhmWjilCg3+aQI08U2MfktrLAyvYB3b3g4Qz0=,tag:sah2sQggyN3gx8bPwodsFw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:ZL6uHg==,iv:10t/YpxHuJGdFTbe7vK4gtWE3Y6VknMljC3k5h0+dpQ=,tag:jw498nt78TITFuqUOaYK9Q==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:/PsqEHZJqtju,iv:RgafCJbJPpUT2sB6Ri8N3iU4PHb+1B2mGGHZ50eCnOs=,tag:FDN5P8MR9yXVugrQCTUVTA==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:RfTFCpvhBOLk6M1sBqfYEXk44RQ2KYLM8mDAA+75XA==,iv:LA3TRrMcHE+9csN6mVpmEAKM5uj4cP5iGCLQqYuZDvU=,tag:cUWqm6xyA3z77HBHjx3AbA==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:XLOm7W/KLak5nN2SHyWLmCgwOA7byMhQ4R3sRTxTTg==,iv:SvN/LZx2lkDDLL/pLoXnW7I6629aXZvFUvR48g6sHeA=,tag:XdzJZ6V9selLglQUoGjolQ==,type:str]
    AUTHENTIK_EMAIL__HOST: ENC[AES256_GCM,data:F64PnYFeHMUNBLhKR7t6k6d5qv3I,iv:TosMnQQ0lzenmgMBeB6uIHzdOAtn+cGafI7M5PyOip0=,tag:7Ck2nYVsvl5TZg/MfhY0gA==,type:str]
    AUTHENTIK_EMAIL__PORT: ENC[AES256_GCM,data:sFUc,iv:A5Vxmq2sgRmhjmaHr9OfzBMz5R8fzi1bT+tXJZBRxt8=,tag:eg7l3MGJqlz/eCKnqoy5Og==,type:int]
    AUTHENTIK_EMAIL__USERNAME: ENC[AES256_GCM,data:CN5rP+zW7t9BcBNFvJWhW3FvzbkdIL5e,iv:15wMGHMmKreEN+NtRcRjODonEBp2BdjXjCTEH7I72Lg=,tag:1ZObUXw66a8Ktmerg5pVtQ==,type:str]
    AUTHENTIK_EMAIL__PASSWORD: ENC[AES256_GCM,data:sTnAh8jyCf/DelEjToBVp0AeCpA+EtB3uV7scPRPTJx03/KxHF2rItcUA1oOGO12vU9XiSG5FyIt5vU+dr6Jtg==,iv:QUehwTHwwIyVw3+otMTn2ItjBFPOXkAq7EkXcypXc4E=,tag:DoGgsGQx+08W7wBFjjlROA==,type:str]
    AUTHENTIK_EMAIL__USE_TLS: ENC[AES256_GCM,data:ywkW7w==,iv:I8ZokVrdNaJSdeIOKrqfP2nhpv/blNBGlMpxhC7vvoA=,tag:lDjzpNqeNGIrpGmK4xW8cQ==,type:bool]
    AUTHENTIK_EMAIL__USE_SSL: ENC[AES256_GCM,data:vEL3neM=,iv:vXAigQYwah44WAJ/SUny40FBWe0OiSXeF1hL0542fJM=,tag:uf3xJo608Dv0Cy4GHOKaew==,type:bool]
    AUTHENTIK_EMAIL__TIMEOUT: ENC[AES256_GCM,data:7Wg=,iv:45TOziwgqxbjRptzyRJU2wXJs0apHgsfHoY/j354I3Q=,tag:EJKKSTZyNu+jOnPPnG5nOA==,type:int]
    AUTHENTIK_EMAIL__FROM: ENC[AES256_GCM,data:N1GLuMAd8D4D2KCtpqorbpmGTRyEQ/Roe3CGtQieDsnWcuOv,iv:ullTX2hR+GKPu/RnxMobeEzynU8cJh+w957dGwvl43k=,tag:0lQ3egKq1xDF4biGSRlJhg==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NGZHN2ptcWNJUk1uZGNv
            cDJrMzJkOFVRRStLdTYvbUFnVVhwYWxQNUZVCjQxY3J5TGRJSDRCQnorU2hhRTJo
            YWNlVGx6ZFRPeVQ5WVhLdzhhZFY3cmMKLS0tIGRhMjFNbW9sRXU0Skc4bWMwZ0l0
            U1VWUEZIa2t1dVRJaVFrODRoZDZzR2sKPbxgFuU5mmGym3l8y9uJ8l3Prj/IPR0P
            1ia3XMZX3o3R69AYY8YJEUPPi5bLlDIs8iT6VO4JZf+LImDtByxs+A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3a1FhcWJiYjJ6bzIwVFMy
            WU5ma2ozSFY1V1lUbUtoL1FKd1kyVEFrbWpJCi95UGFidXA4OW15QTJaYUxGZVJH
            YWVPcUJtSnJjZVJYZVZXMUhnSXBNVjAKLS0tIG9QdmZNdDNEZHlqNmlaaVJyYmp0
            bDBHZnJDMWF2OG0rUXN4UEJnaXF3THMKuHjcQbEvtaMDa8hFYWP3ZtzNwjH48CV2
            C2rStzkWSFf2eYu841y7cSUEa7eEc3v0un+Fhdp7J2NIuxc6NRjG0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T23:46:02Z"
    mac: ENC[AES256_GCM,data:LUyNr/6Nru8I06U3nuVTlcMR2dupAbXO4djQbOfV3Gi8AUhvjSMLT0vWOScnJfXosEkSuj4A3mVKU+f67E134oLzFbqUjoSm1LMYQIHNRV4nP+pqAHQw3FZz4YrviUIoca9dcOjloTKlMzdxzPhgbUkrqyETcsYCJBJ9SEnl96o=,iv:l6rYrzD4OjuEChL4vU0/ZqUT/tv3NPxpnrkKGVkX3nE=,tag:ifbgi3ny1/vlROoCI7LCPA==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
