apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: gitea-db
  namespace: gitea
spec:
  instances: 3
  storage:
    size: 10Gi
    storageClass: longhorn-rc-1
  bootstrap:
    initdb:
      database: gitea
      owner: gitea
  postgresql:
    parameters:
      max_connections: "100"
      max_slot_wal_keep_size: "1GB"
      max_wal_size: "2GB"
      min_wal_size: "512MB"
