apiVersion: v1
kind: Secret
metadata:
    name: gitea-helm-secrets
    namespace: gitea
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:ebmXVnjCcqYcpeATI8RVLbIXsyE0ftrvPdTW/lDPT2QRlAm1ZTvI+ltryXMdJTlzkNOwj0toCKOA1MgYL8aXHVA1v9kIgxYW2AeYa2+sn49kg9tVrd7VW+YNf42U4QJZ3QkGbBYcTZ0j8na57hoKhQ/sotQPK9gGhjZhGQsYJvhVTLldzRThsnSOSmSUx0U2h2xm2ALoslJfJbvshj6vTDwiIKZpDBDGzsSmLYre/MgJFjBx2GuJG5awZt2aL4nQihSOkVfVQL1AhQ359PwrNsLFgEKS0oCAPAGAmAYa+tmdvRqvmuMr56Xge9whR6M12lOtIJn2fAQwWzMgklUzSUX1k74LrL4hDpS0QfCpyNLtztHM0ZPN7MOJ1IGHXtqUJxe+UVOMmUerFd7Nm1k4vYhb8OxO9I2Ys6fvRfmb5Ydpy4xFz+nUBw/yvZSYxmem9NZbM9T1wXj9394OoX7DtqfNTNa8VBHbEohvrheOvFpMoUoK2zlDNMkeOyQWBLnUhRFrepdP9kTO6S1RdG9+d6uBia1+zAJRZJFKJfUHNEIBb4nfrWepSTFswMtmUjO6SsYS6iXoFaCIjsly+a6thxgERsK84lG/SJrfq8uf9T19oLgLK8yKpAU=,iv:f2HamhuWeIV+fyHytHvKr/g1UMd/z/+pCGJweA5CUVQ=,tag:MEq7xwjciPbMRE0OaJIFZw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZXZFMVlhM0Q2bVI4amc1
            bUdUZkdkMTBMcUpKaXdFajlUYkJCeDI2YWdJCkRrdnpoV0hQZlArRXRlbUZKeFE2
            VE5QTHJOZlowekJuZXdWZ2tranI5aU0KLS0tIGIrbkxKQjhvWjB5Y3NReWlQdGlO
            bE9CK01ydlhKZk1GSFlGUU8wRldDSk0KPS6TnYSS0zQvAUKIQB0yhi/50DC4jdfT
            ZjEfo5ljBxmsiN5eYdCwU5pdLC+HvAHU/LKf5Au/8m5UO5PkaisbWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cmxqWGdkTDFKNlhadXJO
            cTdjTmsrdVJRS3drZS9md1hhemVkNXBzcW5FClNtWG9aWU81QUQ0NDFNSVE4QlA3
            VlIwKzRrSjNhVCtpZFVrU0VoMGFncjgKLS0tIG1QVUxGanBNeVNtWndLUGFmTlZj
            VFo1c1oyaTNST2ZXL0N1eUllTHVkYUUKiBax27F+++eavKmtPT6dUVgMQyWGJfae
            URELCptKmJkjtzec2FA8eG2nI8pepd33EDr/DAwDNB/PdU5qGfg89Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:29:59Z"
    mac: ENC[AES256_GCM,data:T7WGvIoW+tRvKlaOGWPmASSlML+I1ThmxNiHESuYv9sjlpxtK/xRBo0eJibUCP84G0sRiaA+kimw0cQw1w8d/Tz1OV8dCKDiS9pm3sygt32no5XGkppdrNrxWXc/plfZ0xDISolKhO7zWvwM1cZ8wIb8A9J2W9n+eA/u7dHNMuc=,iv:LL20BoPNkF6uQLrkHudGkqTIEXfBPltG31QZL2Z0J90=,tag:LP4bDxeWBkH5M6NG2RqR0A==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
