apiVersion: v1
kind: Secret
metadata:
    name: gitea-helm-secrets
    namespace: gitea
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:UMNV2dzqqd7EQDd34rHGZgzzm3wwXu4R1HUzUC5NcdfNew0weCDyy87Dzh6dldi7oCkHcclTEI4ksobz57AKf3eGx3mdKyJeghTR0HbBpTIw69xOEbjd9IYGqt2xxH3klWpjj0IYY9smmaUNSJW2vk+1eaX0rAMUORcLaaiBJx73iwVFRGkd/cyL5+p07H9u7h0FxbAXSBaK/2Cv0FM59Q2CfanN/lGiEtNjPw==,iv:4775xRuEOLQN9VHXSKKSKFoBmO6BvcpPfzq5Svy8EQc=,tag:PVEZN6b2eUoU7Mdn+s5FJw==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbDBuWC9ranZCNTM3N3Bh
            bVM2a281OTRrU0VzVkdCa0lsTUNMR0c3bXlnCklBSXpLRzcxUExpV093a09KN2Zv
            VVQ4bW42cUpqS0xpTlVickFiUnRzOUUKLS0tIGxxMVFja01qMGpSdGQyYXhST21w
            OGt3Qnh0aGZFWkRSZWYxRWNGdGJpSVkKYNQRRV9xBybQT+VATaj2e8rcA/boZpwq
            +sstWyIJvgB+QcZSjvqzmT5/zo2HgiCKX3Gq6LXhMjbFuxH71wP/rQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCVzRjNFVTRG5UNXkxdVJW
            UWpQOWQwand4eWxRSEhSVVJYZzR4UHVBQ0ZzCjJGMVpZb1BORDZVL0hpMVo0VUh5
            U1pJcXdSSFBLbVMwSk1wUjkwT2E4QkkKLS0tIDdCRTQ5b0J4RFA1aFZadzZRazZu
            akxYdzVrODZVbWd2SUtrK0FOSVNIR1EKXuFFMkSDeJETr1YEzO7ZgG1rCbNiAEJH
            pbp8js6fznaD4AmwXGtmCmaWtq5gYKbfjKj/qyIYmCNQVnji6vSfPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T19:37:26Z"
    mac: ENC[AES256_GCM,data:OiwvlWvYevVrbpn2Nf6Scm1JWegZcKcL85yZFSI+bbpt1X1vgE19aHlZcB52tWiYLrS6gFZr2hXC2j4W33p4gqy09KdsIZ81ScSAcFQIKY67pQw12l7j6gI8DRi2e7dMtWxjHbxKRc3/DOspUZh8d5OOLu/Bk9dv7M4nklL+ob0=,iv:i28VFR+soM+tdXJ9qGHrqFEmaU9gZVp++PEXfqHWSps=,tag:L6iLVQYxKc4A7/6kSYwwtw==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
