apiVersion: v1
kind: Secret
metadata:
    name: gitea-helm-secrets
    namespace: gitea
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:0GM0hmP1iSncspGcL5D+jp6fE5UtD6o+S00z3Tvv9r4ldJDDjVUlflXVB8S02gmHeFgUT/qieyNZm8Wjmq+Y3caMcdMOVF4ppXpFkGyzIGIeZxcwAO5kUtx3378p+TbF6DUaxdq0xM4+5Qp9Sfdxf4Mepw2TOWfDlShiprT3tgB7iL0jpWpv7xUooF/TIyPJeCAHUCdBMauX4h0laYfYIF6T7828WDvKz2ae1tuVpj6JIhllpoGm3uv/NCVEAGA/jSWbPBptkvJqYd5EunCisePP2RNuWXDShbQwr7lOfSNhVynRsQ0OrP+ranNuQttsyspApdZExODVA8ileIef474m+LYvEbaHjOQ69JLQWotu29leIjUmK1ZZLYb8Q8qw3ncMbKsFYw8uZhE+VmTjhMg9kfhvqn5O3jqxSRr7TiXarGdfVf27CxVQmG9XDCVCvqlb1xHfARWwkxm4/jA+ullfXNlMKUnaUYyPTKLshkzwb9LiF/iTNLfJpdl9LviIhx6dY6cT8T4NWW2YpvvOatEHiCQwXGR1/ImgNoFaLIeR7Vnf27gGPR/PGUfv35WUW7X/pdgaSa/BTDQBl6angolPWxcOjpIO4nEZHYhLE+y2rgv1bMwN0OFApnggSQ==,iv:o2oLmyA+e2DtT998rEKiaPJMSLN6Ed3JkR8ouZzKG6c=,tag:gDlQ4FaWa/ts9Ts0LJ+T2g==,type:str]
sops:
    age:
        - recipient: age1ejzmv648srczvsw42sv0wq9725ck6d4g3q28gskwgg5kfslqnywq92gm7f
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtZXZFMVlhM0Q2bVI4amc1
            bUdUZkdkMTBMcUpKaXdFajlUYkJCeDI2YWdJCkRrdnpoV0hQZlArRXRlbUZKeFE2
            VE5QTHJOZlowekJuZXdWZ2tranI5aU0KLS0tIGIrbkxKQjhvWjB5Y3NReWlQdGlO
            bE9CK01ydlhKZk1GSFlGUU8wRldDSk0KPS6TnYSS0zQvAUKIQB0yhi/50DC4jdfT
            ZjEfo5ljBxmsiN5eYdCwU5pdLC+HvAHU/LKf5Au/8m5UO5PkaisbWw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14rr3w2m7egq0tx8l89fzd0d8ldgdfw6tmxpc4csjgtulwd949eesuuxslr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cmxqWGdkTDFKNlhadXJO
            cTdjTmsrdVJRS3drZS9md1hhemVkNXBzcW5FClNtWG9aWU81QUQ0NDFNSVE4QlA3
            VlIwKzRrSjNhVCtpZFVrU0VoMGFncjgKLS0tIG1QVUxGanBNeVNtWndLUGFmTlZj
            VFo1c1oyaTNST2ZXL0N1eUllTHVkYUUKiBax27F+++eavKmtPT6dUVgMQyWGJfae
            URELCptKmJkjtzec2FA8eG2nI8pepd33EDr/DAwDNB/PdU5qGfg89Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-03T18:18:55Z"
    mac: ENC[AES256_GCM,data:DXhfmxwIAJ2wbadqBSKr7aPQ9LOPl7csQ1ipZ3pNhJE7g8gUIs3QMAS6m0zb2pkmEeBNXDyEudE3Jebvn/pS3Ca7fUC59Vpfpz62+sODlu28p9kWY/Crr8RIn3BfMHxYOInm20jcZZmCfmsuWFh/y2Ar+GCUcF+HyqmByT45lj0=,iv:KN17P57b+lWs2H0AyaPaFWLKdZA0/yttbrKRlMVz6VY=,tag:4ZxNp9da8zxl6jXHF5UzVQ==,type:str]
    encrypted_regex: ^(data|stringData|email)$
    version: 3.12.2
