apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami
  namespace: whoami
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-cert-issuer"
spec:
  tls:
    - hosts:
        - "*.tyrongabriel.com"
        - "tyrongabriel.com"
      secretName: whoami-tls
  rules:
    - host: "*.tyrongabriel.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
    - host: "tyrongabriel.com"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: whoami
                port:
                  number: 80
